# Generated by Django 5.1.4 on 2026-04-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Ism familiya')),
                ('phone', models.CharField(max_length=13, verbose_name='Telefon')),
                ('source', models.CharField(choices=[('instagram', 'Instagram'), ('telegram', 'Telegram'), ('referral', 'Tavsiya'), ('website', 'Sayt'), ('other', 'Boshqa')], default='other', max_length=20, verbose_name='Manba')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('thinking', "O'ylayapti"), ('trial', 'Sinov darsida'), ('converted', "To'lov qildi"), ('lost', "Yo'qotildi")], default='new', max_length=20, verbose_name='Holat')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('trial_date', models.DateField(blank=True, null=True, verbose_name='Sinov dars sanasi')),
                ('lost_reason', models.CharField(blank=True, max_length=255, verbose_name="Yo'qotish sababi")),
                ('converted_at', models.DateTimeField(blank=True, null=True, verbose_name='Talabaga aylangan vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lid',
                'verbose_name_plural': 'Lidlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('call', "Qo'ng'iroq"), ('note', 'Eslatma'), ('status_changed', "Holat o'zgartirildi"), ('sms_sent', 'SMS yuborildi')], max_length=30)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Faoliyat',
                'verbose_name_plural': 'Faoliyatlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
