# Generated by Django 5.1.4 on 2026-04-21 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL, verbose_name="Mas'ul xodim"),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leads.lead'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', '-created_at'], name='leads_lead_status_7559b2_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['phone'], name='leads_lead_phone_709d42_idx'),
        ),
    ]
