# Generated by Django 3.1.2 on 2026-04-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('no_answer', "Bog'lanib bo'lmadi"), ('thinking', "O'ylayapti"), ('trial', 'Sinov darsida'), ('converted', "To'lov qildi"), ('lost', "Yo'qotildi")], default='new', max_length=20, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='leadactivity',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
